language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

virtualenv:
  system_site_packages: true

before_install:
  - "sudo apt-get install python-dbus python-gobject"

install:
  - "pip install nose coveralls flake8"

script:
  - "flake8 $(find . -iname '*.py')"
  - "nosetests --with-coverage --cover-package=pyconnman tests"

after_success:
  - "coveralls"
